on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: Linter
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: linting
      uses: alexanderdamiani/pylinter@v1.4.0
      with:
        python-root: '.'
        flake8-flags: '--max-line-length=88'
        fail-on-isort: false
        mypy-ignore-dirs-files: 'tests/'